import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  tutorialSidebar: [
    'index',
    'getting-started',
    'releases',
    {
      type: 'category',
      label: 'Foundations',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'foundations/index',
      },
      items: [
        'foundations/colors',
        'foundations/spacing',
        'foundations/iconography',
        'foundations/typography',
      ],
    },
    {
      type: 'category',
      label: 'Componentes',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'components/index',
      },
      items: [
        {
          type: 'category',
          label: 'Button',
          collapsed: false,
          className: 'component-category',
          link: {
            type: 'doc',
            id: 'components/button/index',
          },
          items: [
            {
              type: 'doc',
              id: 'components/button/implementation',
              label: 'Implementación',
              className: 'sidebar-hidden-item',
            },
            {
              type: 'doc',
              id: 'components/button/accessibility',
              label: 'Accesibilidad',
              className: 'sidebar-hidden-item',
            },
          ],
        },
      ],
    },
    {
      type: 'doc',
      id: 'contributing/index',
      label: 'Contributing',
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
